### ISSUE TITLE
Migrate from VSTS to TFS

### ISSUE THREAD

**Issue by randy-wong** [giuliov/WitSync#27]
Does this tool support migrating from VSTS to TFS?

**Comment by giuliov** [comment]
I stopped working on this tool long ago. You should look at https://github.com/nkdAgility/azure-devops-migration-tools or https://github.com/microsoft/vsts-work-item-migrator instead.

**Comment by randy-wong** [comment]
Thanks for the quick response and suggestions! I am going to see if I can modify your tool for my uses.
